---
title: "Travel"
toc: true
---

*A work in progress* 

The closest airport to the wedding venue is Portland International Airport (PDX). It is a one-hour drive from the airport to Hood River, and a further 20 minutes to the wedding venue.

### Flights into Portland

We recommend that you **book your flights early**. Oregon is a big tourist destination in the Summer, and flights can get expensive, or "spendy" as the locals might say. 

- JetBlue and Alaska Airlines offer direct flights from Boston Logan to PDX.
- If you are flying from across the pond, there are direct flights to PDX from London Heathrow, Amsterdam, Frankfurt, and Keflavik, Iceland. There are also direct flights from Dublin to some other West Coast cities, including an Aer Lingus route to Seattle.
- Are you looking for a deal? We recommend checking first for connecting flights through bigger West Coast hubs like Los Angeles (LAX), San Francisco, Seattle, or Vancouver, BC.

#### **Flight discounts**

**Group discounts** <br> The Coens love to travel in a horde, so why not save some money? If 10 or more of you are planning to travel on the same flights, you can get a discount. To arrange with [Alaska Airlines](https://www.alaskaair.com/content/group-travel/groups-travel-overview?lid=nav:book-group&int=AS_NAV_Book_GroupTravel_-prodID:GroupTravel&semid=Google%7C%7CSEMGenDSA%7C%7C&gad_source=1&gclid=CjwKCAiA34S7BhAtEiwACZzv4SBypY9fp5jwxXDB7eofo7DF_XsA9V440G5SDgsxhNz6Sa2XJSzIahoCLlsQAvD_BwE&gclsrc=aw.ds) call 1-800-445-4435; with JetBlue fill out the form at the bottom of [this webpage](https://www.jetblue.com/traveling-together/group-travel).

**Individual discounts** <br> If you are flying on Alaska Airlines to and from PDX, we have a discount code* you can use to book directly with the airline. This entitles you to 5% off your flight from select airports. *Details to follow*.

### From Portland to Hood River

Renting a car offers you the most convenience, but if you would like to avoid renting a car you have [some options](https://visithoodriver.com/transportation/).

### From Hood River to the venue

We will be offering shuttles from the Holiday Inn and the Hood River Hotel.